inputSize = 42;
numHiddenUnits = 200;
numClasses = 6;
maxEpochs = 30;
miniBatchSize = 10;
trainMethod = 'adam';
initLearnRate = 5e-4;

layers = [ ...
    sequenceInputLayer(inputSize)
    lstmLayer(numHiddenUnits,'OutputMode','last')
    fullyConnectedLayer(numClasses)
    softmaxLayer
    classificationLayer];

options = trainingOptions(trainMethod, ...
    'ExecutionEnvironment','auto', ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'GradientThreshold',1, ...
    'InitialLearnRate', initLearnRate, ...
    'Verbose',false, ...
    'Plots','training-progress', ...
    'Shuffle','once');

class = categorical(trainingClass);
net = trainNetwork(trainingData,class,layers,options);